name: Production Release

on: 
  push:
    branches: [ "main" ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Build Project
      run: |
        npm install
        npm run build
    
    # TODO: Enable testing
    #- name: Test
      #run: 
        #ng test --watch=false --browsers=ChromeHeadless
    
    - name: Sync files to Staging Site
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ vars.prod_server }}
        username: ${{ secrets.prod_username }}
        password: ${{ secrets.prod_password }}
        local-dir: ./dist/grantgupton/
